//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm.CrmCommon.OptionSets
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum goal_fiscalperiod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quarter1 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quarter2 = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quarter3 = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quarter4 = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		January = 101,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		February = 102,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		March = 103,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		April = 104,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		May = 105,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		June = 106,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		July = 107,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		August = 108,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		September = 109,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		October = 110,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		November = 111,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		December = 112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Semester1 = 201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Semester2 = 202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Annual = 301,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		P1 = 401,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		P2 = 402,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		P3 = 403,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		P4 = 404,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		P5 = 405,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		P6 = 406,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		P7 = 407,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		P8 = 408,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		P9 = 409,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		P10 = 410,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		P11 = 411,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		P12 = 412,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		P13 = 413,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum goal_fiscalyear
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2038 = 2038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2037 = 2037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2036 = 2036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2035 = 2035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2034 = 2034,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2033 = 2033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2032 = 2032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2031 = 2031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2030 = 2030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2029 = 2029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2028 = 2028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2027 = 2027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2026 = 2026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2025 = 2025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2024 = 2024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2023 = 2023,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2022 = 2022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2021 = 2021,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2020 = 2020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2019 = 2019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2018 = 2018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2017 = 2017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2016 = 2016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2015 = 2015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2014 = 2014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2013 = 2013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2012 = 2012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2011 = 2011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2010 = 2010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2009 = 2009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2008 = 2008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2007 = 2007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2006 = 2006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2005 = 2005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2004 = 2004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2003 = 2003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2002 = 2002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2001 = 2001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY2000 = 2000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1999 = 1999,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1998 = 1998,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1997 = 1997,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1996 = 1996,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1995 = 1995,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1994 = 1994,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1993 = 1993,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1992 = 1992,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1991 = 1991,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1990 = 1990,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1989 = 1989,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1988 = 1988,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1987 = 1987,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1986 = 1986,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1985 = 1985,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1984 = 1984,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1983 = 1983,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1982 = 1982,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1981 = 1981,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1980 = 1980,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1979 = 1979,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1978 = 1978,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1977 = 1977,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1976 = 1976,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1975 = 1975,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1974 = 1974,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1973 = 1973,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1972 = 1972,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1971 = 1971,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FY1970 = 1970,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum metric_goaltype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Money = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Decimal = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Integer = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum componentstate
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Published = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unpublished = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deleted = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeletedUnpublished = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum workflowlog_objecttypecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemJob = 4700,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkflowSession = 4710,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum qooiproduct_propertiesconfigurationstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Edit = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rectify = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotConfigured = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum purchasetimeframe
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Immediate = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThisQuarter = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NextQuarter = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThisYear = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unknown = 4,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum need
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Musthave = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Shouldhave = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Goodtohave = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Noneed = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum connectionrole_category
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Business = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Family = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Social = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sales = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Stakeholder = 1000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SalesTeam = 1001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Service = 1002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum initialcommunication
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Contacted = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotContacted = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum servicestage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Identify = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Research = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolve = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum budgetstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoCommittedBudget = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MayBuy = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CanBuy = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WillBuy = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum sharepointdocumentlocation_locationtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		General = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DedicatedforOneNoteIntegration = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum activitypointer_deliveryprioritycode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Low = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Normal = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		High = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum lead_salesstage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Qualify = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum componenttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entity = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Attribute = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Relationship = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AttributePicklistValue = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AttributeLookupValue = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ViewAttribute = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LocalizedLabel = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RelationshipExtraCondition = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptionSet = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityRelationship = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityRelationshipRole = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityRelationshipRelationships = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ManagedProperty = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityKey = 14,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Role = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RolePrivilege = 21,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DisplayString = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DisplayStringMap = 23,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Form = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Organization = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SavedQuery = 26,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Workflow = 29,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Report = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReportEntity = 32,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReportCategory = 33,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReportVisibility = 34,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Attachment = 35,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailTemplate = 36,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ContractTemplate = 37,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KBArticleTemplate = 38,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MailMergeTemplate = 39,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DuplicateRule = 44,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DuplicateRuleCondition = 45,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityMap = 46,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AttributeMap = 47,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonCommand = 48,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonContextGroup = 49,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonCustomization = 50,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonRule = 52,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonTabToCommandMap = 53,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonDiff = 55,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SavedQueryVisualization = 59,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemForm = 60,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebResource = 61,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SiteMap = 62,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConnectionRole = 63,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FieldSecurityProfile = 70,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FieldPermission = 71,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PluginType = 90,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PluginAssembly = 91,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SDKMessageProcessingStep = 92,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SDKMessageProcessingStepImage = 93,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServiceEndpoint = 95,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RoutingRule = 150,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RoutingRuleItem = 151,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SLA = 152,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SLAItem = 153,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConvertRule = 154,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConvertRuleItem = 155,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HierarchyRule = 65,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum activitypointer_activitytypecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fax = 4204,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneCall = 4210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Letter = 4207,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServiceActivity = 4214,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityClose = 4208,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrderClose = 4209,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuoteClose = 4211,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CaseResolution = 4206,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CampaignResponse = 4401,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CampaignActivity = 4402,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulkOperation = 4406,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecurringAppointment = 4251,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum workflow_runas
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Owner = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CallingUser = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum qooi_pricingerrorcode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DetailError = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingPriceLevel = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InactivePriceLevel = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingQuantity = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingUnitPrice = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingProduct = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidProduct = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingPricingCode = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidPricingCode = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingUOM = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProductNotInPriceLevel = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingPriceLevelAmount = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingPriceLevelPercentage = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingPrice = 14,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingCurrentCost = 15,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingStandardCost = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidPriceLevelAmount = 17,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidPriceLevelPercentage = 18,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidPrice = 19,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidCurrentCost = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidStandardCost = 21,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidRoundingPolicy = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidRoundingOption = 23,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidRoundingAmount = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PriceCalculationError = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidDiscountType = 26,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DiscountTypeInvalidState = 27,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidDiscount = 28,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidQuantity = 29,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidPricingPrecision = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingProductDefaultUOM = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingProductUOMSchedule = 32,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InactiveDiscountType = 33,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidPriceLevelCurrency = 34,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PriceAttributeOutOfRange = 35,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BaseCurrencyAttributeOverflow = 36,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BaseCurrencyAttributeUnderflow = 37,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum sharepoint_validationstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotValidated = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Invalid = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Valid = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Couldnotvalidate = 5,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum emailserverprofile_authenticationprotocol
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AutoDetect = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Negotiate = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NTLM = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Basic = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum convertrule_channelactivity
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneCall = 4210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServiceActivity = 4214,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SocialActivity = 4216,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum socialactivity_postmessagetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PublicMessage = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PrivateMessage = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum syncattributemapping_syncdirection
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ToExchange = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ToCRM = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Bidirectional = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum workflow_stage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Preoperation = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Postoperation = 40,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum dependencytype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionInternal = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Published = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unpublished = 4,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum socialprofile_community
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Facebook = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Twitter = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum field_security_permission_type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotAllowed = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Allowed = 4,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum purchaseprocess
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Individual = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Committee = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unknown = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum opportunity_salesstage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Qualify = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Develop = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Propose = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Close = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum qooiproduct_producttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Product = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Bundle = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RequiredBundleProduct = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptionalBundleProduct = 4,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum processstage_category
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Qualify = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Develop = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Propose = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Close = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Identify = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Research = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolve = 6,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum sharepoint_validationstatusreason
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThisrecordsURLhasnotbeenvalidated = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThisrecordsURLisvalid = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThisrecordsURLisnotvalid = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TheURLschemesofMicrosoftDynamicsCRMandSharePointaredifferent = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TheURLcouldnotbeaccessedbecauseofInternetExplorersecuritysettings = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Authenticationfailure = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Invalidcertificates = 7,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum incident_caseorigincode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Phone = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Web = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Facebook = 2483,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Twitter = 3986,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum recurrencerule_monthofyear
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidMonthOfYear = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		January = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		February = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		March = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		April = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		May = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		June = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		July = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		August = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		September = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		October = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		November = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		December = 12,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum principalsyncattributemapping_syncdirection
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ToExchange = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ToCRM = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Bidirectional = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactAccountRoleCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DecisionMaker = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Employee = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Influencer = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactAddress1_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BillTo = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ShipTo = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Primary = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 4,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactAddress1_FreightTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FOB = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoCharge = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactAddress1_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Airborne = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DHL = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FedEx = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UPS = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostalMail = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FullLoad = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WillCall = 7,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactAddress2_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactAddress2_FreightTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactAddress2_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactAddress3_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactAddress3_FreightTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactAddress3_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactCustomerSizeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactCustomerTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactEducationCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactFamilyStatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Single = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Married = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Divorced = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Widowed = 4,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactGenderCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Male = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Female = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactHasChildrenCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactLeadSourceCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactPaymentTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net30 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_210Net30 = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net45 = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net60 = 4,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactPreferredAppointmentDayCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sunday = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Monday = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Tuesday = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Wednesday = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Thursday = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Friday = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Saturday = 6,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactPreferredAppointmentTimeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Morning = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Afternoon = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Evening = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactPreferredContactMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Any = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Phone = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fax = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Mail = 5,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum contact_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0001.0117")]
	public enum ContactTerritoryCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
}
